spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 1000

---
spring.config.activate.on-profile: test

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:auth;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  mail:
    host: host

security:
  jwt:
    access-secret-key: 5ZCno4gJ5QAnL7s6h5vbyWNMWz/RbmGpOXPooCZUI2g=
    refresh-secret-key: H1lYB7BuPya5f3XfKBQQ0WdQ03CYjNJJMMZETFqf6w8=

---
spring.config.activate.on-profile: local

spring:
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

security:
  jwt:
    access-secret-key: ${ACCESS_SECRET_KEY}
    refresh-secret-key: ${REFRESH_SECRET_KEY}

---
spring.config.activate.on-profile: dev

security:
  jwt:
    access-secret-key: ${ACCESS_SECRET_KEY}
    refresh-secret-key: ${REFRESH_SECRET_KEY}

spring:
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
